### ISSUE TITLE
add formatting option using black

### ISSUE THREAD

**Issue by sivanbecker** [ministryofjustice/mt940-writer#13]
i like using black to format my code in python.
you have linting and i think a good formatting according to known standards is a good complimentary.

once the code is also formatted, CI should check that new code is also formatted.

**Comment by ushkarev** [comment]
whilst `black` _is_ rather popular, we take it to be too dogmatic. i’m having a quick look at [ruff](https://docs.astral.sh/ruff/) which might be a reasonable compromise.

**Comment by sivanbecker** [comment]
did not encounter ruff till now. I'll take a look. thanks

**Comment by ushkarev** [comment]
i’ve swapped flake8 for ruff
https://github.com/ministryofjustice/mt940-writer/commit/615cf446a11e964c5055db105caabcc531627875
and it seems pretty good for formatting, but i’m not totally convinced that the code style checking we had is all preserved 🤔

**Comment by ushkarev** [comment]
hmm i don’t love ruff’s linting config because you don’t seem to get a great set of default rules (e.g. checking indentation is in “preview” and, to me, that’s like the most important one!). now i cannot decide whether to go back to flake8…

https://github.com/ministryofjustice/mt940-writer/commit/9eb51c8f46f4e4477335c7eaf45f1c4f4922fc1f

i’m quite happy with ruff’s formatting however.
